/** @types */

// details
export const GET_SHOW_DETAILS_START = 'GET_SHOW_DETAILS_INIT';
export const GET_SHOW_DETAILS_SUCCESS = 'GET_SHOW_DETAILS_SUCCESS';
export const GET_SHOW_DETAILS_FAIL = 'GET_SHOW_DETAILS_FAIL';

// episodes
export const GET_EPISODES_LIST_START = 'GET_EPISODES_LIST_INIT';
export const GET_EPISODES_LIST_SUCCESS = 'GET_EPISODES_LIST_SUCCESS';
export const GET_EPISODES_LIST_FAIL = 'GET_EPISODES_LIST_FAIL';
